// Public NH DOT/GRANIT Towns layer snapshot, checked 2026-09-19 UTC.
// Includes unincorporated places, not just incorporated municipalities.
// Source: https://maps.dot.nh.gov/arcgis_server/rest/services/Boundaries/NHDOT_BOUNDARIES_Towns/FeatureServer/2
export const nhPlaces = [
  {
    id: "nh-dot-001",
    name: "Acworth",
    county: "Sullivan",
    sourceName: "ACWORTH",
  },
  {
    id: "nh-dot-003",
    name: "Albany",
    county: "Carroll",
    sourceName: "ALBANY",
  },
  {
    id: "nh-dot-005",
    name: "Alexandria",
    county: "Grafton",
    sourceName: "ALEXANDRIA",
  },
  {
    id: "nh-dot-007",
    name: "Allenstown",
    county: "Merrimack",
    sourceName: "ALLENSTOWN",
  },
  {
    id: "nh-dot-009",
    name: "Alstead",
    county: "Cheshire",
    sourceName: "ALSTEAD",
  },
  {
    id: "nh-dot-011",
    name: "Alton",
    county: "Belknap",
    sourceName: "ALTON",
  },
  {
    id: "nh-dot-013",
    name: "Amherst",
    county: "Hillsborough",
    sourceName: "AMHERST",
  },
  {
    id: "nh-dot-015",
    name: "Andover",
    county: "Merrimack",
    sourceName: "ANDOVER",
  },
  {
    id: "nh-dot-017",
    name: "Antrim",
    county: "Hillsborough",
    sourceName: "ANTRIM",
  },
  {
    id: "nh-dot-019",
    name: "Ashland",
    county: "Grafton",
    sourceName: "ASHLAND",
  },
  {
    id: "nh-dot-021",
    name: "Atkinson",
    county: "Rockingham",
    sourceName: "ATKINSON",
  },
  {
    id: "nh-dot-507",
    name: "Atkinson - Gilmanton Academy Grant",
    county: "Coos",
    sourceName: "ATKINSON - GILMANTON ACADEMY GRANT",
  },
  {
    id: "nh-dot-023",
    name: "Auburn",
    county: "Rockingham",
    sourceName: "AUBURN",
  },
  {
    id: "nh-dot-025",
    name: "Barnstead",
    county: "Belknap",
    sourceName: "BARNSTEAD",
  },
  {
    id: "nh-dot-027",
    name: "Barrington",
    county: "Strafford",
    sourceName: "BARRINGTON",
  },
  {
    id: "nh-dot-029",
    name: "Bartlett",
    county: "Carroll",
    sourceName: "BARTLETT",
  },
  {
    id: "nh-dot-031",
    name: "Bath",
    county: "Grafton",
    sourceName: "BATH",
  },
  {
    id: "nh-dot-033",
    name: "Beans Grant",
    county: "Coos",
    sourceName: "BEANS GRANT",
  },
  {
    id: "nh-dot-035",
    name: "Beans Purchase",
    county: "Coos",
    sourceName: "BEANS PURCHASE",
  },
  {
    id: "nh-dot-037",
    name: "Bedford",
    county: "Hillsborough",
    sourceName: "BEDFORD",
  },
  {
    id: "nh-dot-039",
    name: "Belmont",
    county: "Belknap",
    sourceName: "BELMONT",
  },
  {
    id: "nh-dot-041",
    name: "Bennington",
    county: "Hillsborough",
    sourceName: "BENNINGTON",
  },
  {
    id: "nh-dot-043",
    name: "Benton",
    county: "Grafton",
    sourceName: "BENTON",
  },
  {
    id: "nh-dot-045",
    name: "Berlin",
    county: "Coos",
    sourceName: "BERLIN",
  },
  {
    id: "nh-dot-047",
    name: "Bethlehem",
    county: "Grafton",
    sourceName: "BETHLEHEM",
  },
  {
    id: "nh-dot-049",
    name: "Boscawen",
    county: "Merrimack",
    sourceName: "BOSCAWEN",
  },
  {
    id: "nh-dot-051",
    name: "Bow",
    county: "Merrimack",
    sourceName: "BOW",
  },
  {
    id: "nh-dot-053",
    name: "Bradford",
    county: "Merrimack",
    sourceName: "BRADFORD",
  },
  {
    id: "nh-dot-055",
    name: "Brentwood",
    county: "Rockingham",
    sourceName: "BRENTWOOD",
  },
  {
    id: "nh-dot-057",
    name: "Bridgewater",
    county: "Grafton",
    sourceName: "BRIDGEWATER",
  },
  {
    id: "nh-dot-059",
    name: "Bristol",
    county: "Grafton",
    sourceName: "BRISTOL",
  },
  {
    id: "nh-dot-061",
    name: "Brookfield",
    county: "Carroll",
    sourceName: "BROOKFIELD",
  },
  {
    id: "nh-dot-063",
    name: "Brookline",
    county: "Hillsborough",
    sourceName: "BROOKLINE",
  },
  {
    id: "nh-dot-065",
    name: "Cambridge",
    county: "Coos",
    sourceName: "CAMBRIDGE",
  },
  {
    id: "nh-dot-067",
    name: "Campton",
    county: "Grafton",
    sourceName: "CAMPTON",
  },
  {
    id: "nh-dot-069",
    name: "Canaan",
    county: "Grafton",
    sourceName: "CANAAN",
  },
  {
    id: "nh-dot-071",
    name: "Candia",
    county: "Rockingham",
    sourceName: "CANDIA",
  },
  {
    id: "nh-dot-073",
    name: "Canterbury",
    county: "Merrimack",
    sourceName: "CANTERBURY",
  },
  {
    id: "nh-dot-075",
    name: "Carroll",
    county: "Coos",
    sourceName: "CARROLL",
  },
  {
    id: "nh-dot-077",
    name: "Center Harbor",
    county: "Belknap",
    sourceName: "CENTER HARBOR",
  },
  {
    id: "nh-dot-079",
    name: "Chandlers Purchase",
    county: "Coos",
    sourceName: "CHANDLERS PURCHASE",
  },
  {
    id: "nh-dot-081",
    name: "Charlestown",
    county: "Sullivan",
    sourceName: "CHARLESTOWN",
  },
  {
    id: "nh-dot-083",
    name: "Chatham",
    county: "Carroll",
    sourceName: "CHATHAM",
  },
  {
    id: "nh-dot-085",
    name: "Chester",
    county: "Rockingham",
    sourceName: "CHESTER",
  },
  {
    id: "nh-dot-087",
    name: "Chesterfield",
    county: "Cheshire",
    sourceName: "CHESTERFIELD",
  },
  {
    id: "nh-dot-089",
    name: "Chichester",
    county: "Merrimack",
    sourceName: "CHICHESTER",
  },
  {
    id: "nh-dot-091",
    name: "Claremont",
    county: "Sullivan",
    sourceName: "CLAREMONT",
  },
  {
    id: "nh-dot-093",
    name: "Clarksville",
    county: "Coos",
    sourceName: "CLARKSVILLE",
  },
  {
    id: "nh-dot-095",
    name: "Colebrook",
    county: "Coos",
    sourceName: "COLEBROOK",
  },
  {
    id: "nh-dot-097",
    name: "Columbia",
    county: "Coos",
    sourceName: "COLUMBIA",
  },
  {
    id: "nh-dot-099",
    name: "Concord",
    county: "Merrimack",
    sourceName: "CONCORD",
  },
  {
    id: "nh-dot-101",
    name: "Conway",
    county: "Carroll",
    sourceName: "CONWAY",
  },
  {
    id: "nh-dot-103",
    name: "Cornish",
    county: "Sullivan",
    sourceName: "CORNISH",
  },
  {
    id: "nh-dot-105",
    name: "Crawfords Purchase",
    county: "Coos",
    sourceName: "CRAWFORDS PURCHASE",
  },
  {
    id: "nh-dot-107",
    name: "Croydon",
    county: "Sullivan",
    sourceName: "CROYDON",
  },
  {
    id: "nh-dot-501",
    name: "Cutts Grant",
    county: "Coos",
    sourceName: "CUTTS GRANT",
  },
  {
    id: "nh-dot-109",
    name: "Dalton",
    county: "Coos",
    sourceName: "DALTON",
  },
  {
    id: "nh-dot-111",
    name: "Danbury",
    county: "Merrimack",
    sourceName: "DANBURY",
  },
  {
    id: "nh-dot-113",
    name: "Danville",
    county: "Rockingham",
    sourceName: "DANVILLE",
  },
  {
    id: "nh-dot-115",
    name: "Deerfield",
    county: "Rockingham",
    sourceName: "DEERFIELD",
  },
  {
    id: "nh-dot-117",
    name: "Deering",
    county: "Hillsborough",
    sourceName: "DEERING",
  },
  {
    id: "nh-dot-119",
    name: "Derry",
    county: "Rockingham",
    sourceName: "DERRY",
  },
  {
    id: "nh-dot-503",
    name: "Dixs Grant",
    county: "Coos",
    sourceName: "DIXS GRANT",
  },
  {
    id: "nh-dot-121",
    name: "Dixville",
    county: "Coos",
    sourceName: "DIXVILLE",
  },
  {
    id: "nh-dot-123",
    name: "Dorchester",
    county: "Grafton",
    sourceName: "DORCHESTER",
  },
  {
    id: "nh-dot-125",
    name: "Dover",
    county: "Strafford",
    sourceName: "DOVER",
  },
  {
    id: "nh-dot-127",
    name: "Dublin",
    county: "Cheshire",
    sourceName: "DUBLIN",
  },
  {
    id: "nh-dot-129",
    name: "Dummer",
    county: "Coos",
    sourceName: "DUMMER",
  },
  {
    id: "nh-dot-131",
    name: "Dunbarton",
    county: "Merrimack",
    sourceName: "DUNBARTON",
  },
  {
    id: "nh-dot-133",
    name: "Durham",
    county: "Strafford",
    sourceName: "DURHAM",
  },
  {
    id: "nh-dot-135",
    name: "East Kingston",
    county: "Rockingham",
    sourceName: "EAST KINGSTON",
  },
  {
    id: "nh-dot-137",
    name: "Easton",
    county: "Grafton",
    sourceName: "EASTON",
  },
  {
    id: "nh-dot-139",
    name: "Eaton",
    county: "Carroll",
    sourceName: "EATON",
  },
  {
    id: "nh-dot-141",
    name: "Effingham",
    county: "Carroll",
    sourceName: "EFFINGHAM",
  },
  {
    id: "nh-dot-143",
    name: "Ellsworth",
    county: "Grafton",
    sourceName: "ELLSWORTH",
  },
  {
    id: "nh-dot-145",
    name: "Enfield",
    county: "Grafton",
    sourceName: "ENFIELD",
  },
  {
    id: "nh-dot-147",
    name: "Epping",
    county: "Rockingham",
    sourceName: "EPPING",
  },
  {
    id: "nh-dot-149",
    name: "Epsom",
    county: "Merrimack",
    sourceName: "EPSOM",
  },
  {
    id: "nh-dot-151",
    name: "Errol",
    county: "Coos",
    sourceName: "ERROL",
  },
  {
    id: "nh-dot-505",
    name: "Ervings Location",
    county: "Coos",
    sourceName: "ERVINGS LOCATION",
  },
  {
    id: "nh-dot-153",
    name: "Exeter",
    county: "Rockingham",
    sourceName: "EXETER",
  },
  {
    id: "nh-dot-155",
    name: "Farmington",
    county: "Strafford",
    sourceName: "FARMINGTON",
  },
  {
    id: "nh-dot-157",
    name: "Fitzwilliam",
    county: "Cheshire",
    sourceName: "FITZWILLIAM",
  },
  {
    id: "nh-dot-159",
    name: "Francestown",
    county: "Hillsborough",
    sourceName: "FRANCESTOWN",
  },
  {
    id: "nh-dot-161",
    name: "Franconia",
    county: "Grafton",
    sourceName: "FRANCONIA",
  },
  {
    id: "nh-dot-163",
    name: "Franklin",
    county: "Merrimack",
    sourceName: "FRANKLIN",
  },
  {
    id: "nh-dot-165",
    name: "Freedom",
    county: "Carroll",
    sourceName: "FREEDOM",
  },
  {
    id: "nh-dot-167",
    name: "Fremont",
    county: "Rockingham",
    sourceName: "FREMONT",
  },
  {
    id: "nh-dot-169",
    name: "Gilford",
    county: "Belknap",
    sourceName: "GILFORD",
  },
  {
    id: "nh-dot-171",
    name: "Gilmanton",
    county: "Belknap",
    sourceName: "GILMANTON",
  },
  {
    id: "nh-dot-173",
    name: "Gilsum",
    county: "Cheshire",
    sourceName: "GILSUM",
  },
  {
    id: "nh-dot-175",
    name: "Goffstown",
    county: "Hillsborough",
    sourceName: "GOFFSTOWN",
  },
  {
    id: "nh-dot-177",
    name: "Gorham",
    county: "Coos",
    sourceName: "GORHAM",
  },
  {
    id: "nh-dot-179",
    name: "Goshen",
    county: "Sullivan",
    sourceName: "GOSHEN",
  },
  {
    id: "nh-dot-181",
    name: "Grafton",
    county: "Grafton",
    sourceName: "GRAFTON",
  },
  {
    id: "nh-dot-183",
    name: "Grantham",
    county: "Sullivan",
    sourceName: "GRANTHAM",
  },
  {
    id: "nh-dot-185",
    name: "Greenfield",
    county: "Hillsborough",
    sourceName: "GREENFIELD",
  },
  {
    id: "nh-dot-187",
    name: "Greenland",
    county: "Rockingham",
    sourceName: "GREENLAND",
  },
  {
    id: "nh-dot-189",
    name: "Greens Grant",
    county: "Coos",
    sourceName: "GREENS GRANT",
  },
  {
    id: "nh-dot-191",
    name: "Greenville",
    county: "Hillsborough",
    sourceName: "GREENVILLE",
  },
  {
    id: "nh-dot-193",
    name: "Groton",
    county: "Grafton",
    sourceName: "GROTON",
  },
  {
    id: "nh-dot-509",
    name: "Hadleys Purchase",
    county: "Coos",
    sourceName: "HADLEYS PURCHASE",
  },
  {
    id: "nh-dot-511",
    name: "Hales Location",
    county: "Carroll",
    sourceName: "HALES LOCATION",
  },
  {
    id: "nh-dot-195",
    name: "Hampstead",
    county: "Rockingham",
    sourceName: "HAMPSTEAD",
  },
  {
    id: "nh-dot-197",
    name: "Hampton",
    county: "Rockingham",
    sourceName: "HAMPTON",
  },
  {
    id: "nh-dot-199",
    name: "Hampton Falls",
    county: "Rockingham",
    sourceName: "HAMPTON FALLS",
  },
  {
    id: "nh-dot-201",
    name: "Hancock",
    county: "Hillsborough",
    sourceName: "HANCOCK",
  },
  {
    id: "nh-dot-203",
    name: "Hanover",
    county: "Grafton",
    sourceName: "HANOVER",
  },
  {
    id: "nh-dot-205",
    name: "Harrisville",
    county: "Cheshire",
    sourceName: "HARRISVILLE",
  },
  {
    id: "nh-dot-207",
    name: "Harts Location",
    county: "Carroll",
    sourceName: "HARTS LOCATION",
  },
  {
    id: "nh-dot-209",
    name: "Haverhill",
    county: "Grafton",
    sourceName: "HAVERHILL",
  },
  {
    id: "nh-dot-211",
    name: "Hebron",
    county: "Grafton",
    sourceName: "HEBRON",
  },
  {
    id: "nh-dot-213",
    name: "Henniker",
    county: "Merrimack",
    sourceName: "HENNIKER",
  },
  {
    id: "nh-dot-215",
    name: "Hill",
    county: "Merrimack",
    sourceName: "HILL",
  },
  {
    id: "nh-dot-217",
    name: "Hillsborough",
    county: "Hillsborough",
    sourceName: "HILLSBOROUGH",
  },
  {
    id: "nh-dot-219",
    name: "Hinsdale",
    county: "Cheshire",
    sourceName: "HINSDALE",
  },
  {
    id: "nh-dot-221",
    name: "Holderness",
    county: "Grafton",
    sourceName: "HOLDERNESS",
  },
  {
    id: "nh-dot-223",
    name: "Hollis",
    county: "Hillsborough",
    sourceName: "HOLLIS",
  },
  {
    id: "nh-dot-225",
    name: "Hooksett",
    county: "Merrimack",
    sourceName: "HOOKSETT",
  },
  {
    id: "nh-dot-227",
    name: "Hopkinton",
    county: "Merrimack",
    sourceName: "HOPKINTON",
  },
  {
    id: "nh-dot-229",
    name: "Hudson",
    county: "Hillsborough",
    sourceName: "HUDSON",
  },
  {
    id: "nh-dot-231",
    name: "Jackson",
    county: "Carroll",
    sourceName: "JACKSON",
  },
  {
    id: "nh-dot-233",
    name: "Jaffrey",
    county: "Cheshire",
    sourceName: "JAFFREY",
  },
  {
    id: "nh-dot-235",
    name: "Jefferson",
    county: "Coos",
    sourceName: "JEFFERSON",
  },
  {
    id: "nh-dot-237",
    name: "Keene",
    county: "Cheshire",
    sourceName: "KEENE",
  },
  {
    id: "nh-dot-239",
    name: "Kensington",
    county: "Rockingham",
    sourceName: "KENSINGTON",
  },
  {
    id: "nh-dot-241",
    name: "Kilkenny",
    county: "Coos",
    sourceName: "KILKENNY",
  },
  {
    id: "nh-dot-243",
    name: "Kingston",
    county: "Rockingham",
    sourceName: "KINGSTON",
  },
  {
    id: "nh-dot-245",
    name: "Laconia",
    county: "Belknap",
    sourceName: "LACONIA",
  },
  {
    id: "nh-dot-247",
    name: "Lancaster",
    county: "Coos",
    sourceName: "LANCASTER",
  },
  {
    id: "nh-dot-249",
    name: "Landaff",
    county: "Grafton",
    sourceName: "LANDAFF",
  },
  {
    id: "nh-dot-251",
    name: "Langdon",
    county: "Sullivan",
    sourceName: "LANGDON",
  },
  {
    id: "nh-dot-253",
    name: "Lebanon",
    county: "Grafton",
    sourceName: "LEBANON",
  },
  {
    id: "nh-dot-255",
    name: "Lee",
    county: "Strafford",
    sourceName: "LEE",
  },
  {
    id: "nh-dot-257",
    name: "Lempster",
    county: "Sullivan",
    sourceName: "LEMPSTER",
  },
  {
    id: "nh-dot-259",
    name: "Lincoln",
    county: "Grafton",
    sourceName: "LINCOLN",
  },
  {
    id: "nh-dot-261",
    name: "Lisbon",
    county: "Grafton",
    sourceName: "LISBON",
  },
  {
    id: "nh-dot-263",
    name: "Litchfield",
    county: "Hillsborough",
    sourceName: "LITCHFIELD",
  },
  {
    id: "nh-dot-265",
    name: "Littleton",
    county: "Grafton",
    sourceName: "LITTLETON",
  },
  {
    id: "nh-dot-267",
    name: "Livermore",
    county: "Grafton",
    sourceName: "LIVERMORE",
  },
  {
    id: "nh-dot-269",
    name: "Londonderry",
    county: "Rockingham",
    sourceName: "LONDONDERRY",
  },
  {
    id: "nh-dot-271",
    name: "Loudon",
    county: "Merrimack",
    sourceName: "LOUDON",
  },
  {
    id: "nh-dot-273",
    name: "Low - Burbanks Grant",
    county: "Coos",
    sourceName: "LOW - BURBANKS GRANT",
  },
  {
    id: "nh-dot-275",
    name: "Lyman",
    county: "Grafton",
    sourceName: "LYMAN",
  },
  {
    id: "nh-dot-277",
    name: "Lyme",
    county: "Grafton",
    sourceName: "LYME",
  },
  {
    id: "nh-dot-279",
    name: "Lyndeborough",
    county: "Hillsborough",
    sourceName: "LYNDEBOROUGH",
  },
  {
    id: "nh-dot-281",
    name: "Madbury",
    county: "Strafford",
    sourceName: "MADBURY",
  },
  {
    id: "nh-dot-283",
    name: "Madison",
    county: "Carroll",
    sourceName: "MADISON",
  },
  {
    id: "nh-dot-285",
    name: "Manchester",
    county: "Hillsborough",
    sourceName: "MANCHESTER",
  },
  {
    id: "nh-dot-287",
    name: "Marlborough",
    county: "Cheshire",
    sourceName: "MARLBOROUGH",
  },
  {
    id: "nh-dot-289",
    name: "Marlow",
    county: "Cheshire",
    sourceName: "MARLOW",
  },
  {
    id: "nh-dot-291",
    name: "Martins Location",
    county: "Coos",
    sourceName: "MARTINS LOCATION",
  },
  {
    id: "nh-dot-293",
    name: "Mason",
    county: "Hillsborough",
    sourceName: "MASON",
  },
  {
    id: "nh-dot-295",
    name: "Meredith",
    county: "Belknap",
    sourceName: "MEREDITH",
  },
  {
    id: "nh-dot-297",
    name: "Merrimack",
    county: "Hillsborough",
    sourceName: "MERRIMACK",
  },
  {
    id: "nh-dot-299",
    name: "Middleton",
    county: "Strafford",
    sourceName: "MIDDLETON",
  },
  {
    id: "nh-dot-301",
    name: "Milan",
    county: "Coos",
    sourceName: "MILAN",
  },
  {
    id: "nh-dot-303",
    name: "Milford",
    county: "Hillsborough",
    sourceName: "MILFORD",
  },
  {
    id: "nh-dot-305",
    name: "Millsfield",
    county: "Coos",
    sourceName: "MILLSFIELD",
  },
  {
    id: "nh-dot-307",
    name: "Milton",
    county: "Strafford",
    sourceName: "MILTON",
  },
  {
    id: "nh-dot-311",
    name: "Monroe",
    county: "Grafton",
    sourceName: "MONROE",
  },
  {
    id: "nh-dot-309",
    name: "Mont Vernon",
    county: "Hillsborough",
    sourceName: "MONT VERNON",
  },
  {
    id: "nh-dot-313",
    name: "Moultonborough",
    county: "Carroll",
    sourceName: "MOULTONBOROUGH",
  },
  {
    id: "nh-dot-315",
    name: "Nashua",
    county: "Hillsborough",
    sourceName: "NASHUA",
  },
  {
    id: "nh-dot-317",
    name: "Nelson",
    county: "Cheshire",
    sourceName: "NELSON",
  },
  {
    id: "nh-dot-319",
    name: "New Boston",
    county: "Hillsborough",
    sourceName: "NEW BOSTON",
  },
  {
    id: "nh-dot-323",
    name: "New Castle",
    county: "Rockingham",
    sourceName: "NEW CASTLE",
  },
  {
    id: "nh-dot-325",
    name: "New Durham",
    county: "Strafford",
    sourceName: "NEW DURHAM",
  },
  {
    id: "nh-dot-329",
    name: "New Hampton",
    county: "Belknap",
    sourceName: "NEW HAMPTON",
  },
  {
    id: "nh-dot-333",
    name: "New Ipswich",
    county: "Hillsborough",
    sourceName: "NEW IPSWICH",
  },
  {
    id: "nh-dot-335",
    name: "New London",
    county: "Merrimack",
    sourceName: "NEW LONDON",
  },
  {
    id: "nh-dot-321",
    name: "Newbury",
    county: "Merrimack",
    sourceName: "NEWBURY",
  },
  {
    id: "nh-dot-327",
    name: "Newfields",
    county: "Rockingham",
    sourceName: "NEWFIELDS",
  },
  {
    id: "nh-dot-331",
    name: "Newington",
    county: "Rockingham",
    sourceName: "NEWINGTON",
  },
  {
    id: "nh-dot-337",
    name: "Newmarket",
    county: "Rockingham",
    sourceName: "NEWMARKET",
  },
  {
    id: "nh-dot-339",
    name: "Newport",
    county: "Sullivan",
    sourceName: "NEWPORT",
  },
  {
    id: "nh-dot-341",
    name: "Newton",
    county: "Rockingham",
    sourceName: "NEWTON",
  },
  {
    id: "nh-dot-345",
    name: "North Hampton",
    county: "Rockingham",
    sourceName: "NORTH HAMPTON",
  },
  {
    id: "nh-dot-343",
    name: "Northfield",
    county: "Merrimack",
    sourceName: "NORTHFIELD",
  },
  {
    id: "nh-dot-347",
    name: "Northumberland",
    county: "Coos",
    sourceName: "NORTHUMBERLAND",
  },
  {
    id: "nh-dot-349",
    name: "Northwood",
    county: "Rockingham",
    sourceName: "NORTHWOOD",
  },
  {
    id: "nh-dot-351",
    name: "Nottingham",
    county: "Rockingham",
    sourceName: "NOTTINGHAM",
  },
  {
    id: "nh-dot-513",
    name: "Odell",
    county: "Coos",
    sourceName: "ODELL",
  },
  {
    id: "nh-dot-353",
    name: "Orange",
    county: "Grafton",
    sourceName: "ORANGE",
  },
  {
    id: "nh-dot-355",
    name: "Orford",
    county: "Grafton",
    sourceName: "ORFORD",
  },
  {
    id: "nh-dot-357",
    name: "Ossipee",
    county: "Carroll",
    sourceName: "OSSIPEE",
  },
  {
    id: "nh-dot-359",
    name: "Pelham",
    county: "Hillsborough",
    sourceName: "PELHAM",
  },
  {
    id: "nh-dot-361",
    name: "Pembroke",
    county: "Merrimack",
    sourceName: "PEMBROKE",
  },
  {
    id: "nh-dot-363",
    name: "Peterborough",
    county: "Hillsborough",
    sourceName: "PETERBOROUGH",
  },
  {
    id: "nh-dot-365",
    name: "Piermont",
    county: "Grafton",
    sourceName: "PIERMONT",
  },
  {
    id: "nh-dot-367",
    name: "Pinkhams Grant",
    county: "Coos",
    sourceName: "PINKHAMS GRANT",
  },
  {
    id: "nh-dot-369",
    name: "Pittsburg",
    county: "Coos",
    sourceName: "PITTSBURG",
  },
  {
    id: "nh-dot-371",
    name: "Pittsfield",
    county: "Merrimack",
    sourceName: "PITTSFIELD",
  },
  {
    id: "nh-dot-373",
    name: "Plainfield",
    county: "Sullivan",
    sourceName: "PLAINFIELD",
  },
  {
    id: "nh-dot-375",
    name: "Plaistow",
    county: "Rockingham",
    sourceName: "PLAISTOW",
  },
  {
    id: "nh-dot-377",
    name: "Plymouth",
    county: "Grafton",
    sourceName: "PLYMOUTH",
  },
  {
    id: "nh-dot-379",
    name: "Portsmouth",
    county: "Rockingham",
    sourceName: "PORTSMOUTH",
  },
  {
    id: "nh-dot-381",
    name: "Randolph",
    county: "Coos",
    sourceName: "RANDOLPH",
  },
  {
    id: "nh-dot-383",
    name: "Raymond",
    county: "Rockingham",
    sourceName: "RAYMOND",
  },
  {
    id: "nh-dot-385",
    name: "Richmond",
    county: "Cheshire",
    sourceName: "RICHMOND",
  },
  {
    id: "nh-dot-387",
    name: "Rindge",
    county: "Cheshire",
    sourceName: "RINDGE",
  },
  {
    id: "nh-dot-389",
    name: "Rochester",
    county: "Strafford",
    sourceName: "ROCHESTER",
  },
  {
    id: "nh-dot-391",
    name: "Rollinsford",
    county: "Strafford",
    sourceName: "ROLLINSFORD",
  },
  {
    id: "nh-dot-393",
    name: "Roxbury",
    county: "Cheshire",
    sourceName: "ROXBURY",
  },
  {
    id: "nh-dot-395",
    name: "Rumney",
    county: "Grafton",
    sourceName: "RUMNEY",
  },
  {
    id: "nh-dot-397",
    name: "Rye",
    county: "Rockingham",
    sourceName: "RYE",
  },
  {
    id: "nh-dot-399",
    name: "Salem",
    county: "Rockingham",
    sourceName: "SALEM",
  },
  {
    id: "nh-dot-401",
    name: "Salisbury",
    county: "Merrimack",
    sourceName: "SALISBURY",
  },
  {
    id: "nh-dot-403",
    name: "Sanbornton",
    county: "Belknap",
    sourceName: "SANBORNTON",
  },
  {
    id: "nh-dot-405",
    name: "Sandown",
    county: "Rockingham",
    sourceName: "SANDOWN",
  },
  {
    id: "nh-dot-407",
    name: "Sandwich",
    county: "Carroll",
    sourceName: "SANDWICH",
  },
  {
    id: "nh-dot-497",
    name: "Sargents Purchase",
    county: "Coos",
    sourceName: "SARGENTS PURCHASE",
  },
  {
    id: "nh-dot-409",
    name: "Seabrook",
    county: "Rockingham",
    sourceName: "SEABROOK",
  },
  {
    id: "nh-dot-515",
    name: "Second College Grant",
    county: "Coos",
    sourceName: "SECOND COLLEGE GRANT",
  },
  {
    id: "nh-dot-411",
    name: "Sharon",
    county: "Hillsborough",
    sourceName: "SHARON",
  },
  {
    id: "nh-dot-413",
    name: "Shelburne",
    county: "Coos",
    sourceName: "SHELBURNE",
  },
  {
    id: "nh-dot-415",
    name: "Somersworth",
    county: "Strafford",
    sourceName: "SOMERSWORTH",
  },
  {
    id: "nh-dot-417",
    name: "South Hampton",
    county: "Rockingham",
    sourceName: "SOUTH HAMPTON",
  },
  {
    id: "nh-dot-419",
    name: "Springfield",
    county: "Sullivan",
    sourceName: "SPRINGFIELD",
  },
  {
    id: "nh-dot-421",
    name: "Stark",
    county: "Coos",
    sourceName: "STARK",
  },
  {
    id: "nh-dot-423",
    name: "Stewartstown",
    county: "Coos",
    sourceName: "STEWARTSTOWN",
  },
  {
    id: "nh-dot-425",
    name: "Stoddard",
    county: "Cheshire",
    sourceName: "STODDARD",
  },
  {
    id: "nh-dot-427",
    name: "Strafford",
    county: "Strafford",
    sourceName: "STRAFFORD",
  },
  {
    id: "nh-dot-429",
    name: "Stratford",
    county: "Coos",
    sourceName: "STRATFORD",
  },
  {
    id: "nh-dot-431",
    name: "Stratham",
    county: "Rockingham",
    sourceName: "STRATHAM",
  },
  {
    id: "nh-dot-517",
    name: "Success",
    county: "Coos",
    sourceName: "SUCCESS",
  },
  {
    id: "nh-dot-499",
    name: "Sugar Hill",
    county: "Grafton",
    sourceName: "SUGAR HILL",
  },
  {
    id: "nh-dot-433",
    name: "Sullivan",
    county: "Cheshire",
    sourceName: "SULLIVAN",
  },
  {
    id: "nh-dot-435",
    name: "Sunapee",
    county: "Sullivan",
    sourceName: "SUNAPEE",
  },
  {
    id: "nh-dot-437",
    name: "Surry",
    county: "Cheshire",
    sourceName: "SURRY",
  },
  {
    id: "nh-dot-439",
    name: "Sutton",
    county: "Merrimack",
    sourceName: "SUTTON",
  },
  {
    id: "nh-dot-441",
    name: "Swanzey",
    county: "Cheshire",
    sourceName: "SWANZEY",
  },
  {
    id: "nh-dot-443",
    name: "Tamworth",
    county: "Carroll",
    sourceName: "TAMWORTH",
  },
  {
    id: "nh-dot-445",
    name: "Temple",
    county: "Hillsborough",
    sourceName: "TEMPLE",
  },
  {
    id: "nh-dot-447",
    name: "Thompson - Meserves Purchase",
    county: "Coos",
    sourceName: "THOMPSON - MESERVES PURCHASE",
  },
  {
    id: "nh-dot-449",
    name: "Thornton",
    county: "Grafton",
    sourceName: "THORNTON",
  },
  {
    id: "nh-dot-451",
    name: "Tilton",
    county: "Belknap",
    sourceName: "TILTON",
  },
  {
    id: "nh-dot-453",
    name: "Troy",
    county: "Cheshire",
    sourceName: "TROY",
  },
  {
    id: "nh-dot-455",
    name: "Tuftonboro",
    county: "Carroll",
    sourceName: "TUFTONBORO",
  },
  {
    id: "nh-dot-457",
    name: "Unity",
    county: "Sullivan",
    sourceName: "UNITY",
  },
  {
    id: "nh-dot-459",
    name: "Wakefield",
    county: "Carroll",
    sourceName: "WAKEFIELD",
  },
  {
    id: "nh-dot-461",
    name: "Walpole",
    county: "Cheshire",
    sourceName: "WALPOLE",
  },
  {
    id: "nh-dot-463",
    name: "Warner",
    county: "Merrimack",
    sourceName: "WARNER",
  },
  {
    id: "nh-dot-465",
    name: "Warren",
    county: "Grafton",
    sourceName: "WARREN",
  },
  {
    id: "nh-dot-467",
    name: "Washington",
    county: "Sullivan",
    sourceName: "WASHINGTON",
  },
  {
    id: "nh-dot-469",
    name: "Waterville Valley",
    county: "Grafton",
    sourceName: "WATERVILLE VALLEY",
  },
  {
    id: "nh-dot-471",
    name: "Weare",
    county: "Hillsborough",
    sourceName: "WEARE",
  },
  {
    id: "nh-dot-473",
    name: "Webster",
    county: "Merrimack",
    sourceName: "WEBSTER",
  },
  {
    id: "nh-dot-475",
    name: "Wentworth",
    county: "Grafton",
    sourceName: "WENTWORTH",
  },
  {
    id: "nh-dot-477",
    name: "Wentworths Location",
    county: "Coos",
    sourceName: "WENTWORTHS LOCATION",
  },
  {
    id: "nh-dot-479",
    name: "Westmoreland",
    county: "Cheshire",
    sourceName: "WESTMORELAND",
  },
  {
    id: "nh-dot-481",
    name: "Whitefield",
    county: "Coos",
    sourceName: "WHITEFIELD",
  },
  {
    id: "nh-dot-483",
    name: "Wilmot",
    county: "Merrimack",
    sourceName: "WILMOT",
  },
  {
    id: "nh-dot-485",
    name: "Wilton",
    county: "Hillsborough",
    sourceName: "WILTON",
  },
  {
    id: "nh-dot-487",
    name: "Winchester",
    county: "Cheshire",
    sourceName: "WINCHESTER",
  },
  {
    id: "nh-dot-489",
    name: "Windham",
    county: "Rockingham",
    sourceName: "WINDHAM",
  },
  {
    id: "nh-dot-491",
    name: "Windsor",
    county: "Hillsborough",
    sourceName: "WINDSOR",
  },
  {
    id: "nh-dot-493",
    name: "Wolfeboro",
    county: "Carroll",
    sourceName: "WOLFEBORO",
  },
  {
    id: "nh-dot-495",
    name: "Woodstock",
    county: "Grafton",
    sourceName: "WOODSTOCK",
  },
] as const;
